image:
  repository: orenavinoam11/playground
  tag: app
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  port: 5000

env:
  DB_HOST: db
  DB_PORT: "5432"
  DB_NAME: playground
  DB_USER: playground

resources: {}
