{{- range $name, $svc := .Values.services }}
{{- if $svc.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secret
  labels:
    {{- include "playground.labels" $ | nindent 4 }}
    app: {{ $name }}
type: Opaque
stringData:
  {{- range $key, $value := $svc.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
